-- MySQL Script generated by MySQL Workbench
-- Tue May 17 14:25:49 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecommerce` DEFAULT CHARACTER SET utf8mb4 ;
USE `ecommerce` ;

-- -----------------------------------------------------
-- Table `ecommerce`.`CLIENTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`CLIENTS` (
  `id_client` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `passeword` CHAR(40) NOT NULL,
  `adresse1` VARCHAR(255) NOT NULL,
  `adresse2` VARCHAR(255) NULL,
  `adresse3` VARCHAR(255) NULL,
  `cp` VARCHAR(5) NOT NULL,
  `ville` VARCHAR(255) NOT NULL,
  `tel` VARCHAR(10) NULL,
  PRIMARY KEY (`id_client`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`COMMANDES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`COMMANDES` (
  `id_COMMANDE` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(45) NOT NULL,
  `date` DATETIME NOT NULL,
  `libelle` VARCHAR(255) NOT NULL,
  `id_client` INT NOT NULL,
  PRIMARY KEY (`id_COMMANDE`),
  INDEX `fk_COMMANDE_CLIENTS_idx` (`id_client` ASC)  ,
  CONSTRAINT `fk_COMMANDE_CLIENTS`
    FOREIGN KEY (`id_client`)
    REFERENCES `ecommerce`.`CLIENTS` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`CATEGORIE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`CATEGORIE` (
  `id_CATEGORIE` INT NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_CATEGORIE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`TVA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`TVA` (
  `id_tva` INT NOT NULL AUTO_INCREMENT,
  `taux` FLOAT NOT NULL,
  `libelle` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tva`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`ARTICLES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`ARTICLES` (
  `id_ARTICLES` INT NOT NULL AUTO_INCREMENT,
  `designiation` VARCHAR(45) NOT NULL,
  `puht` FLOAT NOT NULL,
  `poids` FLOAT NOT NULL,
  `description` TEXT NULL,
  `id_CATEGORIE` INT NOT NULL,
  `id_tva` INT NOT NULL,
  PRIMARY KEY (`id_ARTICLES`),
  INDEX `fk_ARTICLES_CATEGORIE1_idx` (`id_CATEGORIE` ASC)  ,
  INDEX `fk_ARTICLES_TVA1_idx` (`id_tva` ASC)  ,
  CONSTRAINT `fk_ARTICLES_CATEGORIE1`
    FOREIGN KEY (`id_CATEGORIE`)
    REFERENCES `ecommerce`.`CATEGORIE` (`id_CATEGORIE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ARTICLES_TVA1`
    FOREIGN KEY (`id_tva`)
    REFERENCES `ecommerce`.`TVA` (`id_tva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`ARTICLES_has_COMMANDES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`ARTICLES_has_COMMANDES` (
  `id_ARTICLES` INT NOT NULL,
  `id_COMMANDE` INT NOT NULL,
  `qte` INT NOT NULL,
  PRIMARY KEY (`id_ARTICLES`, `id_COMMANDE`),
  INDEX `fk_ARTICLES_has_COMMANDES_COMMANDES1_idx` (`id_COMMANDE` ASC) ,
  INDEX `fk_ARTICLES_has_COMMANDES_ARTICLES1_idx` (`id_ARTICLES` ASC) ,
  CONSTRAINT `fk_ARTICLES_has_COMMANDES_ARTICLES1`
    FOREIGN KEY (`id_ARTICLES`)
    REFERENCES `ecommerce`.`ARTICLES` (`id_ARTICLES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ARTICLES_has_COMMANDES_COMMANDES1`
    FOREIGN KEY (`id_COMMANDE`)
    REFERENCES `ecommerce`.`COMMANDES` (`id_COMMANDE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
